name: doctro
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  progress_indicators: ^1.0.0
  otp_text_field: ^1.1.0
  dotted_line: ^3.0.0
  intl: ^0.17.0
  retrofit: any
  cloud_firestore:
  json_annotation: ^4.0.0
  fluttertoast: ^8.0.8
  form_field_validator: ^1.1.0
  shared_preferences: ^2.0.6
  auto_size_text: ^3.0.0-nullsafety.0
  pinput: ^1.2.0

  numeric_keyboard: ^1.1.0
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  cached_network_image: ^3.1.0
  flutter_spinkit: ^5.1.0
  google_maps_flutter: ^2.0.11
  geolocator: ^8.0.5
  location: ^4.3.0
  share_plus: ^3.0.4
  uuid: ^3.0.5
  http: ^0.13.0

  google_maps_webservice: ^0.0.20-nullsafety.2
  flutter_google_places: ^0.3.0

  google_api_headers: ^1.0.0
  razorpay_flutter: ^1.2.7
  flutter_rating_bar: ^4.0.0
  barcode_widget: ^2.0.1
  html: ^0.15.0
  sqflite: any
  date_picker_timeline: any
  path_provider: any
  logger: ^1.0.0
  onesignal_flutter: ^3.2.8
  flutter_launcher_icons: ^0.9.0
  carousel_slider: ^4.0.0
  flutter_paystack: ^1.0.5+1
  stripe_payment: ^1.1.4
  flutter_credit_card: ^3.0.1
  connectivity: ^3.0.3
  flutter_html: ^3.0.0-alpha.2
  file_picker: ^4.0.0
  permission_handler: ^8.2.2
  flutter_custom_clippers: ^2.0.0
  country_picker: ^2.0.7
  flutterwave: ^1.0.1

  firebase_core: ^1.0.4
  nb_utils: ^4.4.10 # Firebase Core package required to use other firebase services
  firebase_auth: ^1.1.1
  chips_choice: ^2.0.1
  flutter_local_notifications: ^9.0.0
  wakelock: ^0.5.6
  audioplayers: ^0.20.1
  google_fonts: ^2.1.0
  flutter_vector_icons: ^1.0.0
  provider:

    # Used to Save User Data in Database
  firebase_messaging: ^10.0.0   # Used to Send Push Notifications (e.g. New like, Visit and Message)
  firebase_storage:
  introduction_screen: ^2.1.0  # Used to Save User Profile Images on Cloud Storage
  agora_rtc_engine: ^4.0.7

  ntp: ^2.0.0
  localstorage: ^4.0.0+1

  webview_flutter:
  http_auth:
  mobx: ^2.0.5
  flutter_mobx: ^2.0.2

  in_app_purchase: ^0.5.2 # This plugin help us to Sell VIP Subscription Plans in app
  geoflutterfire: ^3.0.0-nullsafety.2 # This plugin help us to query users by geolocation center
  # Used to Select User Country Code
  scoped_model: ^2.0.0-nullsafety.0 # Used to Manage Application State
   # Used to select images from the User's device image library or take a new photo using the camera
  image_cropper: ^1.4.0 # Used to Crop/Rotate Selected images from user's device
   # Used to open link schemes in application or browser

  geocoding: ^2.0.0
  place_picker: ^0.9.19-nullsafety
  shimmer: ^2.0.0 # Used to create placeholder widget while app is loading the image
  timeago: ^3.0.2 # Used to create fuzzy timestamps: (e.g. "3 minutes ago")
  share: ^2.0.1 # Used to share application content in other applications
  flutter_cupertino_datetime_picker: ^2.0.1
  circular_check_box:
  image_picker: ^0.8.4+10

dev_dependencies:
  flutter_test:
    sdk: flutter
  retrofit_generator: any
  build_runner: any
  flutter_native_splash: ^2.0.1+1
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  color_dark: "#1a1a1a"
  image_dark: assets/images/splash.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - lib/localization/languages/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf




  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
